#### Relevant url:
https://medium.com/swlh/how-to-scrape-tweets-by-location-in-python-using-snscrape-8c870fa6ec25#:~:text=There%20are%20two%20ways%20to,as%20part%20of%20their%20profile

In [1]:
import pandas as pd
import snscrape.modules.twitter as sntwitter
import itertools

In [2]:
#Shortened code to fetch the first (i.e. most recent) 100 tweets that contains the phrase data science 
pd.DataFrame(itertools.islice(sntwitter.TwitterSearchScraper(
    '"data science"').get_items(), 100))

,url,date,content,renderedContent,id,user,replyCount,retweetCount,likeCount,quoteCount,...,media,retweetedTweet,quotedTweet,inReplyToTweetId,inReplyToUser,mentionedUsers,coordinates,place,hashtags,cashtags
0,https://twitter.com/siele_justus/status/157303...,2022-09-22 19:52:36+00:00,"@HarunMbaabu if possible, organise for data sc...","@HarunMbaabu if possible, organise for data sc...",1573037567339028483,"{'username': 'siele_justus', 'id': 12463875731...",0,0,0,0,...,None,None,None,NaN,None,"[{'username': 'HarunMbaabu', 'id': 11935383927...",None,None,None,None
1,https://twitter.com/DVCuervo/status/1573037481...,2022-09-22 19:52:15+00:00,#SEOnderground el súper equipo de data science...,#SEOnderground el súper equipo de data science...,1573037481120890881,"{'username': 'DVCuervo', 'id': 277587293, 'dis...",0,0,1,0,...,[{'previewUrl': 'https://pbs.twimg.com/media/F...,None,None,NaN,None,None,None,None,[SEOnderground],None
2,https://twitter.com/machinelearnflx/status/157...,2022-09-22 19:51:39+00:00,eugeneyan/applied-ml: 📚 Papers &amp; tech blog...,eugeneyan/applied-ml: 📚 Papers &amp; tech blog...,1573037327282323462,"{'username': 'machinelearnflx', 'id': 48208042...",0,0,1,0,...,None,None,None,NaN,None,None,None,None,"[DataScience, MachineLearning]",None
3,https://twitter.com/DonBogotano/status/1573037...,2022-09-22 19:50:24+00:00,Una charla muy interesante la de @inkasunka so...,Una charla muy interesante la de @inkasunka so...,1573037012457820168,"{'username': 'DonBogotano', 'id': 345505415, '...",1,0,1,0,...,[{'previewUrl': 'https://pbs.twimg.com/media/F...,None,None,NaN,None,"[{'username': 'inkasunka', 'id': 314778774, 'd...",None,None,"[SEOnderground, SEO]",None
4,https://twitter.com/AbdnCHDS/status/1573036848...,2022-09-22 19:49:45+00:00,Check out @aberdeenuni Open Access Week. Lots ...,Check out @aberdeenuni Open Access Week. Lots ...,1573036848867328002,"{'username': 'AbdnCHDS', 'id': 935544921246793...",0,1,1,0,...,None,None,{'url': 'https://twitter.com/OpenResearchUoA/s...,NaN,None,"[{'username': 'aberdeenuni', 'id': 20427406, '...",None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,https://twitter.com/Willv4_0/status/1573023829...,2022-09-22 18:58:01+00:00,4 Essential Python Projects for Beginners in D...,4 Essential Python Projects for Beginners in D...,1573023829840265217,"{'username': 'Willv4_0', 'id': 31139206, 'disp...",0,1,0,0,...,None,None,None,NaN,None,None,None,None,None,None
96,https://twitter.com/DataSciSalon/status/157302...,2022-09-22 18:57:43+00:00,@DataSciSalon is partnering with @CIOApplicati...,@DataSciSalon is partnering with @CIOApplicati...,1573023756142137344,"{'username': 'DataSciSalon', 'id': 82901872604...",0,0,0,0,...,None,None,None,NaN,None,"[{'username': 'DataSciSalon', 'id': 8290187260...",None,None,None,None
97,https://twitter.com/KaskadaInc/status/15730235...,2022-09-22 18:56:55+00:00,Kaskada provides rapid development and trainin...,Kaskada provides rapid development and trainin...,1573023552776769536,"{'username': 'KaskadaInc', 'id': 9617782160703...",0,1,0,0,...,[{'thumbnailUrl': 'https://pbs.twimg.com/ext_t...,None,None,NaN,None,None,None,None,"[data, development, ml, machinelearning, dataa...",None
98,https://twitter.com/CPetersen_CS/status/157302...,2022-09-22 18:54:39+00:00,"A5) [agreeing with the gang] And, enabling cit...","A5) [agreeing with the gang] And, enabling cit...",1573022985581125632,"{'username': 'CPetersen_CS', 'id': 458979801, ...",0,2,1,0,...,None,None,None,NaN,None,"[{'username': 'nyike', 'id': 16693331, 'displa...",None,None,[ciochat],None
99,https://twitter.com/MatildaKohler3/status/1573...,2022-09-22 18:49:23+00:00,2 in 1 ชุดวิชา Data Science + วิชา Attacking t...,2 in 1 ชุดวิชา Data Science + วิชา Attacking t...,1573021658142515201,"{'username': 'MatildaKohler3', 'id': 153580131...",0,0,0,0,...,None,None,None,NaN,None,None,None,None,None,None

#### The TwitterSearchScraper uses Twitter’s advanced search; for an in depth run down of all its capabilities check out this table — I cannot recommend it enough!

In [7]:
#To find all tweets about pizza in Los Angeles. This can be achieved using the following code:

df_city = pd.DataFrame(itertools.islice(sntwitter.TwitterSearchScraper(
    'pizza near:"Los Angeles" within:10km').get_items(), 50))[['date', 'content']]

#### OR

In [10]:
# Instead of using the city’s name you can use its coordinates:

loc = '34.052235, -118.243683, 10km'
df_coord = pd.DataFrame(itertools.islice(sntwitter.TwitterSearchScraper(
    'pizza geocode:"{}"'.format(loc)).get_items(), 50))[['date', 'content']]

In [13]:
df_city.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   date     50 non-null     datetime64[ns, UTC]
 1   content  50 non-null     object
dtypes: datetime64[ns, UTC](1), object(1)
memory usage: 928.0+ bytes

In [14]:
df_coord.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   date     50 non-null     datetime64[ns, UTC]
 1   content  50 non-null     object
dtypes: datetime64[ns, UTC](1), object(1)
memory usage: 928.0+ bytes

In [31]:
loc = '34.052235, -118.243683, 100km'
df_coord = pd.DataFrame(itertools.islice(sntwitter.TwitterSearchScraper(
    'GoDaddy geocode:"{}"'.format(loc)).get_items(), 5000))[['user', 'date','content']]

df_coord['user_location'] =  df_coord['user'].apply(lambda x: x['location'])
df_coord['user'] =  df_coord['user'].apply(lambda x: x['username'])

In [32]:
df_coord

,user,date,content,user_location
0,tayvano_,2022-09-22 13:19:55+00:00,2️⃣ Liquid CEX\nData breach / PII extraction\n...,"Los Angeles, CA"
1,sethakatz,2022-09-21 20:40:37+00:00,@RSMUSLLP\n@allenmatkins\nCathay Bank\n@ClarkB...,"Los Angeles, CA"
2,RAY_UR6IX,2022-09-20 20:30:07+00:00,"@nandoodles n the last 2 weeks, I notified MyP...",Temecula Ca
3,LigLending,2022-09-20 17:57:09+00:00,Proudly presenting https://t.co/BHqqQMxWaD. Ch...,"Downey, CA"
4,edgybranding,2022-09-20 16:03:47+00:00,Some things you should know about Dan/GoDaddy ...,"Santa Monica, CA"
...,...,...,...,...
1482,FreddieCarthy,2010-10-02 05:20:58+00:00,I downloaded the GoDaddy iPhone app and immedi...,PDX
1483,jasonlankow,2010-08-02 22:41:51+00:00,Cool - 30% off on godaddy.com registrations - ...,meepzorp.eth ꜩ.
1484,__loganc,2010-05-27 03:27:13+00:00,"@lilzaphod just an fyi, looks like lilzaphod.c...","Los Angeles, CA"
1485,grhansen,2010-04-07 17:52:01+00:00,"Since searching for hosting services, it appea...","Stillwater, MN"
1486,jonirvine,2010-03-12 00:43:43+00:00,@djword doesn't look like it is available when...,"Portland, OR, USA"

In [44]:
df_coord.to_csv('tweets within 100 Km of Los Angeles location.csv')

In [30]:
#Initally 'user' column consisted of dictionary of users in each row 
df_coord['user'][0]

{'username': 'tayvano_',
 'id': 19748227,
 'displayname': 'Tay 🦊💙',
 'description': 'building @metamask 🦊 prev ceo-ing @mycrypto 💙 part-time wizard. lethal founder. top assassin ✨ dont come @ me less youre ready to battle 🗡 💖  tay.eth',
 'rawDescription': 'building @metamask 🦊 prev ceo-ing @mycrypto 💙 part-time wizard. lethal founder. top assassin ✨ dont come @ me less youre ready to battle 🗡 💖  tay.eth',
 'descriptionUrls': None,
 'verified': True,
 'created': datetime.datetime(2009, 1, 30, 1, 46, 41, tzinfo=datetime.timezone.utc),
 'followersCount': 57382,
 'friendsCount': 6623,
 'statusesCount': 20900,
 'favouritesCount': 17492,
 'listedCount': 1276,
 'mediaCount': 2440,
 'location': 'Los Angeles, CA',
 'protected': False,
 'linkUrl': 'https://metamask.io/',
 'linkTcourl': 'https://t.co/KiKvfYKyw9',
 'profileImageUrl': 'https://pbs.twimg.com/profile_images/1558729910671183873/RHtt9Zgf_normal.jpg',
 'profileBannerUrl': 'https://pbs.twimg.com/profile_banners/19748227/1405371955',
 'label': None}

In [39]:
df= pd.DataFrame(itertools.islice(sntwitter.TwitterSearchScraper(
    'GoDaddy').get_items(), 10000))[['user','date', 'content']]

df['user_location'] =  df['user'].apply(lambda x: x['location'])
df

,user,date,content,user_location
0,"{'username': 'Braxtonmanley', 'id': 33365139, ...",2022-09-22 22:10:24+00:00,@iamdulma Super underrated graphic design app:...,"Austin, TX"
1,"{'username': 'SGEmail2', 'id': 154764207240801...",2022-09-22 22:10:24+00:00,@GoDaddy - online form error- \nThere was an e...,
2,"{'username': 'Rachelgaffney', 'id': 19592472, ...",2022-09-22 22:09:49+00:00,@GoDaddy I am now on Day #4 of my website not ...,"Dallas,Tx"
3,"{'username': 'marcflood', 'id': 21065058, 'dis...",2022-09-22 22:06:10+00:00,GoDaddy Alternatives and Competitors https://t...,"Dallas, TX"
4,"{'username': 'GoDaddyOSS', 'id': 9595630949376...",2022-09-22 21:59:46+00:00,Experimentation on the brain? Check out our la...,
...,...,...,...,...
9995,"{'username': 'TheGoopyGhost', 'id': 35699406, ...",2022-08-16 10:51:07+00:00,The @GoDaddy tech/SEO expert who answered my c...,
9996,"{'username': 'CmHazza', 'id': 1345464922831007...",2022-08-16 10:38:20+00:00,@kotakmakan @cm0102legends This. I used WiX in...,
9997,"{'username': 'gettaxomate', 'id': 818987754952...",2022-08-16 10:23:29+00:00,Wave Accounting has some worth its cost additi...,
9998,"{'username': 'metanhs', 'id': 1371703825443213...",2022-08-16 10:18:29+00:00,@eddywangping @GoDaddy needs to sort its algor...,United States
9999,"{'username': 'ecarlesi', 'id': 19444180, 'disp...",2022-08-16 10:18:05+00:00,Possible threat on hxxp://mivtop[.]com #godaddy,"Roma, Lazio"

In [42]:
df['user_location'].unique()

array(['Austin, TX', '', 'Dallas,Tx', ..., 'Waterville Maine', 'DK',
       'Logo for your startup in 5min→'], dtype=object)

In [43]:
df.to_csv('10000 tweets of GoDaddy with location.csv')

In [2]:
df= pd.DataFrame(itertools.islice(sntwitter.TwitterSearchScraper(
    'GoDaddy').get_items(), 50000))[['user','date', 'content']]

df['user_location'] =  df['user'].apply(lambda x: x['location'])
df

,user,date,content,user_location
0,"{'username': 'ecarlesi', 'id': 19444180, 'disp...",2022-09-23 08:06:56+00:00,Possible threat on hxxps://securedfirstechcuvi...,"Roma, Lazio"
1,"{'username': 'ARCH1V3S23', 'id': 1498900982209...",2022-09-23 08:04:14+00:00,adobe express why do u nawt hv a layer somethi...,"she/they, minor, works on ⚡️"
2,"{'username': 'hytyjyu', 'id': 1551087273160036...",2022-09-23 08:02:29+00:00,@tsa_gamefi @MetascanPro @JoshMalina @whoisadd...,
3,"{'username': 'ecarlesi', 'id': 19444180, 'disp...",2022-09-23 07:55:09+00:00,Possible threat on hxxp://shivbets[.]com #god...,"Roma, Lazio"
4,"{'username': 'ecarlesi', 'id': 19444180, 'disp...",2022-09-23 07:50:33+00:00,Possible threat on hxxps://rediction-carte-vit...,"Roma, Lazio"
...,...,...,...,...
49995,"{'username': 'IT_news_for_all', 'id': 11321275...",2022-03-17 07:49:42+00:00,Аналитики заметили всплеск бэкдор-инфекций на ...,Україна
49996,"{'username': 'Abhaykottur', 'id': 146734073119...",2022-03-17 07:35:54+00:00,#cybersecurity Hundreds of GoDaddy-hosted site...,
49997,"{'username': 'PentestingN', 'id': 146486877493...",2022-03-17 07:13:57+00:00,Hundreds of GoDaddy-hosted sites backdoored in...,
49998,"{'username': 'mscmt18', 'id': 1150791550999203...",2022-03-17 07:08:54+00:00,Increase in Malware on GoDaddy’s Managed WP Si...,
49999,"{'username': 'ecarlesi', 'id': 19444180, 'disp...",2022-03-17 07:05:17+00:00,Possible threat on hxxps://splinterlads[.]webs...,"Roma, Lazio"

In [17]:
df.to_csv('50000 tweets of GoDaddy from 29-5-20 to 1-11-20.csv')

In [4]:
df['date']

0       2022-09-23 08:06:56+00:00
1       2022-09-23 08:04:14+00:00
2       2022-09-23 08:02:29+00:00
3       2022-09-23 07:55:09+00:00
4       2022-09-23 07:50:33+00:00
                   ...
49995   2022-03-17 07:49:42+00:00
49996   2022-03-17 07:35:54+00:00
49997   2022-03-17 07:13:57+00:00
49998   2022-03-17 07:08:54+00:00
49999   2022-03-17 07:05:17+00:00
Name: date, Length: 50000, dtype: datetime64[ns, UTC]

In [5]:
df['date']=pd.to_datetime(df['date'],errors='coerce')

In [7]:
df.sort_values(by='date',ascending=True,inplace=True)

In [8]:
df

,user,date,content,user_location
49999,"{'username': 'ecarlesi', 'id': 19444180, 'disp...",2022-03-17 07:05:17+00:00,Possible threat on hxxps://splinterlads[.]webs...,"Roma, Lazio"
49998,"{'username': 'mscmt18', 'id': 1150791550999203...",2022-03-17 07:08:54+00:00,Increase in Malware on GoDaddy’s Managed WP Si...,
49997,"{'username': 'PentestingN', 'id': 146486877493...",2022-03-17 07:13:57+00:00,Hundreds of GoDaddy-hosted sites backdoored in...,
49996,"{'username': 'Abhaykottur', 'id': 146734073119...",2022-03-17 07:35:54+00:00,#cybersecurity Hundreds of GoDaddy-hosted site...,
49995,"{'username': 'IT_news_for_all', 'id': 11321275...",2022-03-17 07:49:42+00:00,Аналитики заметили всплеск бэкдор-инфекций на ...,Україна
...,...,...,...,...
4,"{'username': 'ecarlesi', 'id': 19444180, 'disp...",2022-09-23 07:50:33+00:00,Possible threat on hxxps://rediction-carte-vit...,"Roma, Lazio"
3,"{'username': 'ecarlesi', 'id': 19444180, 'disp...",2022-09-23 07:55:09+00:00,Possible threat on hxxp://shivbets[.]com #god...,"Roma, Lazio"
2,"{'username': 'hytyjyu', 'id': 1551087273160036...",2022-09-23 08:02:29+00:00,@tsa_gamefi @MetascanPro @JoshMalina @whoisadd...,
1,"{'username': 'ARCH1V3S23', 'id': 1498900982209...",2022-09-23 08:04:14+00:00,adobe express why do u nawt hv a layer somethi...,"she/they, minor, works on ⚡️"
0,"{'username': 'ecarlesi', 'id': 19444180, 'disp...",2022-09-23 08:06:56+00:00,Possible threat on hxxps://securedfirstechcuvi...,"Roma, Lazio"

In [10]:
df= pd.DataFrame(itertools.islice(sntwitter.TwitterSearchScraper(
    'GoDaddy until:2022-03-17').get_items(), 50000))[['user','date', 'content']]

df['user_location'] =  df['user'].apply(lambda x: x['location'])
df

,user,date,content,user_location
0,"{'username': 'post_status', 'id': 1094276815, ...",2022-03-16 23:57:21+00:00,They lookin' for a System Admin (#WordPress Su...,Dashboard
1,"{'username': 'atlasbooth', 'id': 1376223935407...",2022-03-16 23:57:08+00:00,Yola sucks. 0/10 stars. A lot of effort and th...,South Africa
2,"{'username': 'Jordan80329114', 'id': 116062983...",2022-03-16 23:56:34+00:00,Proudly presenting https://t.co/2CHqfSnUOs. Ch...,"Midland, TX"
3,"{'username': 'ElzafraOficial', 'id': 134410448...",2022-03-16 23:31:12+00:00,É com orgulho que apresentamos o https://t.co/...,São Paulo - Brasil
4,"{'username': 'ryan_zurrin', 'id': 102537018564...",2022-03-16 23:26:26+00:00,"Why I love @GoDaddy: Great customer service, t...","Massachusetts, BerkshireCounty"
...,...,...,...,...
49995,"{'username': 'RealNoraC', 'id': 93231527137272...",2021-09-06 02:59:19+00:00,Had to come back to drop this. #Texas #SnitchS...,Kentucky
49996,"{'username': 'MeachamDr', 'id': 14175453702724...",2021-09-06 02:59:17+00:00,"@thehill Thank you, @GoDaddy!",Metaluna
49997,"{'username': 'wordpressdotcom', 'id': 823905, ...",2021-09-06 02:56:31+00:00,@therapyworksBC @WordPress @GoDaddy That parti...,All over the world
49998,"{'username': 'SuperRacerss', 'id': 82212179530...",2021-09-06 02:56:29+00:00,@kakioptions @Ljsj14831550 @gong_lawrence @bak...,
49999,"{'username': 'cabotammy', 'id': 58594956, 'dis...",2021-09-06 02:53:34+00:00,Hey @GoDaddy FUCK OFF https://t.co/OkePKdGpnw,

In [12]:
df= pd.DataFrame(itertools.islice(sntwitter.TwitterSearchScraper(
    'GoDaddy until:2021-09-6').get_items(), 50000))[['user','date', 'content']]

df['user_location'] =  df['user'].apply(lambda x: x['location'])
df

,user,date,content,user_location
0,"{'username': 'NuvoDiogenes', 'id': 467684598, ...",2021-09-05 23:54:08+00:00,@YtersBitching @whiteboogeyman1 Signing up wit...,USA
1,"{'username': 'correct_brut', 'id': 12787637077...",2021-09-05 23:52:23+00:00,@GoDaddy @stevesilberman What ToS? Can't post...,
2,"{'username': 'pogue25', 'id': 38380611, 'displ...",2021-09-05 23:51:45+00:00,.@GoDaddy cut off Texas Right to Life’s aborti...,Texas
3,"{'username': 'jplyford', 'id': 156153000, 'dis...",2021-09-05 23:50:20+00:00,@TeaBone40265401 @JaneQPublik @TXRightToLife @...,"California, US"
4,"{'username': 'truecourse1', 'id': 136316344138...",2021-09-05 23:50:11+00:00,@crystallinewave @GoDaddy @stevesilberman Inte...,
...,...,...,...,...
49995,"{'username': 'Hernan36171296', 'id': 556998994...",2021-04-05 22:12:00+00:00,Why I love @GoDaddy: confianza https://t.co/gg...,Peru
49996,"{'username': 'igniteBBB', 'id': 10889227606701...",2021-04-05 22:00:11+00:00,We are TWO days away from our International En...,
49997,"{'username': 'Cypher437', 'id': 3716163917, 'd...",2021-04-05 21:53:06+00:00,@BobMcElrath I heard it was a mistake from goD...,
49998,"{'username': 'danielmelo_dm', 'id': 931041456,...",2021-04-05 21:43:26+00:00,@lopp Looks like Godaddy messed this one up. S...,Earth
49999,"{'username': 'iWebzConnect', 'id': 2366750846,...",2021-04-05 21:42:46+00:00,Comparing GoDaddy SSL and PositiveSSL certific...,

In [14]:
df= pd.DataFrame(itertools.islice(sntwitter.TwitterSearchScraper(
    'GoDaddy until:2021-04-5').get_items(), 50000))[['user','date', 'content']]

df['user_location'] =  df['user'].apply(lambda x: x['location'])
df

,user,date,content,user_location
0,"{'username': 'jaime_arias', 'id': 7139822, 'di...",2021-04-04 23:56:11+00:00,Presentamos con orgullo a https://t.co/ECYs0kL...,Colombia
1,"{'username': 'RenameCa', 'id': 137586528132352...",2021-04-04 23:51:11+00:00,This position of Director of the GoDaddy NameF...,
2,"{'username': 'bjsburner', 'id': 442993690, 'di...",2021-04-04 23:22:33+00:00,@John72573060 @YoungSteveyB @mark_my_words92 @...,
3,"{'username': 'laceytech', 'id': 149703977, 'di...",2021-04-04 22:52:34+00:00,GoDaddy Pro Will Kick off 2-Day Expand Event o...,"England, United Kingdom"
4,"{'username': 'soleuscramps', 'id': 13125478188...",2021-04-04 22:41:55+00:00,@patriottakes @APoppaBear Well if only godaddy...,
...,...,...,...,...
49995,"{'username': 'Funnel_Hacker1', 'id': 127337498...",2020-11-01 06:19:19+00:00,"@LegendaryEnergy Hello My People, check out th...",Nigeria
49996,"{'username': 'Funnel_Hacker1', 'id': 127337498...",2020-11-01 06:19:12+00:00,"@washingtonpost Hello My People, check out the...",Nigeria
49997,"{'username': 'Funnel_Hacker1', 'id': 127337498...",2020-11-01 06:19:00+00:00,"@DrGJackBrown Hello My People, check out the e...",Nigeria
49998,"{'username': 'Funnel_Hacker1', 'id': 127337498...",2020-11-01 06:18:48+00:00,"@donwinslow @Yahoo Hello My People, check out ...",Nigeria
49999,"{'username': 'Funnel_Hacker1', 'id': 127337498...",2020-11-01 06:18:31+00:00,"@NPR @waitwait Hello My People, check out the ...",Nigeria

In [16]:
df= pd.DataFrame(itertools.islice(sntwitter.TwitterSearchScraper(
    'GoDaddy until:2020-11-1').get_items(), 50000))[['user','date', 'content']]

df['user_location'] =  df['user'].apply(lambda x: x['location'])
df

,user,date,content,user_location
0,"{'username': 'MRHanrahan', 'id': 23869731, 'di...",2020-10-31 23:45:12+00:00,Legal representation for a reasonable fee.\n h...,"West Palm Beach, Florida"
1,"{'username': 'thedrsec', 'id': 277541083, 'dis...",2020-10-31 23:24:29+00:00,@GoDaddy Do not buy anything from these thieves.,The Great Oglala Lakota Nation
2,"{'username': 'RoselandHerbal1', 'id': 13226500...",2020-10-31 22:46:50+00:00,Proudly presenting https://t.co/FJAC69L6r9. Ch...,
3,"{'username': 'ArtKeller', 'id': 61355243, 'dis...",2020-10-31 22:42:20+00:00,@DrKarlynB @Mailchimp That shit is unacceptabl...,Southwest USA
4,"{'username': 'sportanto', 'id': 283143765, 'di...",2020-10-31 22:33:42+00:00,"Et maintenant, voici https://t.co/G9Yz9xVMwO. ...",Huy (Liege)
...,...,...,...,...
49995,"{'username': 'ClarissaHylton', 'id': 305154863...",2020-05-29 14:40:03+00:00,"I’ve just published my website, check it out a...","Columbus, Ohio"
49996,"{'username': 'WorkSpacesEvent', 'id': 10885424...",2020-05-29 14:37:39+00:00,"Can't wait to unveil Office Hours, our new web...","Palm Springs, CA"
49997,"{'username': 'blondiegraphics', 'id': 44490795...",2020-05-29 14:34:49+00:00,15 social media tips and best practices for 20...,
49998,"{'username': 'SkiperKakao', 'id': 738858404, '...",2020-05-29 14:24:33+00:00,@tasmanianfox у GoDaddy уже несколько лет два ...,St. Petersburg
49999,"{'username': 'Moneypenny', 'id': 73099430, 'di...",2020-05-29 14:23:17+00:00,"While your office doors are closed, it’s more ...",

In [18]:
df= pd.DataFrame(itertools.islice(sntwitter.TwitterSearchScraper(
    'GoDaddy until:2020-5-29').get_items(), 50000))[['user','date', 'content']]

df['user_location'] =  df['user'].apply(lambda x: x['location'])
df

,user,date,content,user_location
0,"{'username': 'spookspatooks', 'id': 9965715653...",2020-05-28 23:58:22+00:00,@jasonwhittier wix is awesome! ive also heard ...,she/her
1,"{'username': 'N28Neila', 'id': 2794879231, 'di...",2020-05-28 23:25:40+00:00,Proudly presenting https://t.co/IaAs9WYFZ5. Ch...,Ontario Canada
2,"{'username': 'Poetsthatdontk1', 'id': 11877746...",2020-05-28 23:22:22+00:00,@jasonwhittier GoDaddy,221B Baker Street
3,"{'username': 'drgrinstead', 'id': 53272646, 'd...",2020-05-28 23:17:38+00:00,Proudly presenting https://t.co/dsuip4xb9U. Ch...,Nampa Idaho
4,"{'username': 'ChaceRandolph', 'id': 1120521332...",2020-05-28 23:12:38+00:00,@jasonwhittier I bought my domains through god...,"Arizona, USA"
...,...,...,...,...
49995,"{'username': 'Vnickel17', 'id': 93052511419349...",2020-01-26 15:49:21+00:00,Proudly presenting https://t.co/fmHbMfFKj0. Ch...,
49996,"{'username': 'drunkSEOrobot', 'id': 8120018443...",2020-01-26 15:46:42+00:00,Godaddy is Adding Local Recommendations in ‘Fo...,6th Dimension
49997,"{'username': 'vicgoinmobilia1', 'id': 12212269...",2020-01-26 15:45:32+00:00,Presentando con orgullo https://t.co/8otCTKK7b...,
49998,"{'username': 'YoungJesus_86', 'id': 1215095908...",2020-01-26 15:45:10+00:00,Proudly presenting https://t.co/N7cnykRlmQ. Ch...,United States
49999,"{'username': 'frankaboutsport', 'id': 12214395...",2020-01-26 15:40:21+00:00,Proudly presenting https://t.co/OBYcKCCqgH. Ch...,

In [21]:
df.to_csv('50000 tweets of GoDaddy from 10-9-19 to 25-1-20.csv')

In [20]:
df= pd.DataFrame(itertools.islice(sntwitter.TwitterSearchScraper(
    'GoDaddy until:2020-1-26').get_items(), 50000))[['user','date', 'content']]

df['user_location'] =  df['user'].apply(lambda x: x['location'])
df

,user,date,content,user_location
0,"{'username': 'LibertyIsALady', 'id': 19808025,...",2020-01-25 23:49:57+00:00,@VelvetBlade @GoDaddy @Stephaniefishm4 @ItIsIM...,Oregon
1,"{'username': 'mdscan1941', 'id': 2796130142, '...",2020-01-25 23:43:24+00:00,Join our most effective music theory classes. ...,"Vaughan, Ontario"
2,"{'username': 'LibertyIsALady', 'id': 19808025,...",2020-01-25 23:39:18+00:00,@VelvetBlade @GoDaddy @Stephaniefishm4 @ItIsIM...,Oregon
3,"{'username': 'LisaLam88628518', 'id': 12077232...",2020-01-25 23:37:09+00:00,Proudly presenting https://t.co/fBVrX6iiPE. Ch...,New York
4,"{'username': 'ADOSBKCERTIFIED', 'id': 31212706...",2020-01-25 23:34:50+00:00,Proudly presenting https://t.co/E8EqumW33p. Ch...,United States
...,...,...,...,...
49995,"{'username': 'TeamedOnwardLLC', 'id': 11166875...",2019-09-10 15:45:12+00:00,Proudly presenting https://t.co/oO5eASul8Z. Ch...,"63 Emerald Street, PMB 504, Ke"
49996,"{'username': 'tmj_webjobs', 'id': 39923029, 'd...",2019-09-10 15:45:06+00:00,We have 57 jobs open today at Robert Half (@Ac...,Worldwide
49997,"{'username': 'GoDaddy', 'id': 14949454, 'displ...",2019-09-10 15:42:46+00:00,@ShadesHues That's amazing! What's the most re...,
49998,"{'username': 'ottersbachs', 'id': 892210033844...",2019-09-10 15:39:28+00:00,Proudly presenting https://t.co/IhH8phjajv. Ch...,"Tampa, FL"
49999,"{'username': 'afdlhost', 'id': 308571422, 'dis...",2019-09-10 15:36:35+00:00,استضافة جودادي | شرح شراء استضافة المواقع جودا...,